#!/bin/sh
#
# TazWeb Helper - Handle bookmarks (no libtaz, usable on any Linux distro)
#

tazweb="$(pwd)/tazweb"
config="$HOME/.config/tazweb"
bm_txt="$config/bookmarks.txt"
bm_html="$config/bookmarks.html"

help() {
	cat << EOT

$(gettext "Usage:") $(basename $0) [bookmarks] --option

$(gettext "Options:")
  --raw       Show raw bookmarks.txt

EOT
}

# HTML 5 header with built-in minimal CSS
html_header() {
	cat << EOT
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<title>TazWeb - Bookmarks</title>
	<style type="text/css">
		body { margin: 2% 10%; font-size: 94%; } ul { padding: 0; }
		h1 { color: #888; border-bottom: 4px solid #888; }
		ul a { text-decoration: none; } ul a:hover { text-decoration: underline; }
		li { list-style-type: none; color: #666; line-height: 1.4em; padding: 0; }
		footer { font-size: 80%; border-top: 1px solid #888; padding: 5px 0; }
		textarea { width: 100%; height: 240px; font-size: 98%; }
	</style>
</head>
<body>
<section id="content">
<h1>TazWeb Bookmarks</h1>
<ul>
EOT
}

# HTML 5 footer
html_footer() {
	cat << EOT
</ul>
</section>
<footer>
	$(cat $bm_txt | wc -l) $(gettext "bookmarks")
</footer>
</body>
</html>
EOT
}

# Generate bookmarks.html
html_bookmarks() {
	html_header > ${bm_html}
	IFS="|"
	cat ${bm_txt} | while read title url null
	do
		cat >> ${bm_html} << EOT
	<li><a href="${url}">${title}</a></li>
EOT
	done
	unset IFS
	html_footer  >> ${bm_html}
	# Security fix from old cgi-bin bookmarks.cgi
	chmod 0600 ${USER}.${USER} ${bm_txt}
}

#
# Commands
#
case "$1" in
	
	-b|bookmarks)
		if [ "$raw" ]; then
			${tazweb} file:///${config}/bookmarks.txt &
		else
			html_bookmarks
			${tazweb} file:///${config}/bookmarks.html &
		fi ;;
	
	*_*) ${1} ;;
	
	*|-h|help) help ;;

esac; exit 0
